import 'modern-normalize';
import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import TanStackProvider from "./components/TanStackProvider/TanStackProvider";
import Header from "./components/Header/Header";

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "TravelTrucks",
  description: "Generated by create next app",

  openGraph: {
    title: "Book campervan- TravelTrucks",
    description: "Generated by create next app.",
    url: "",
    siteName: "TravelTrucks",
    images: [
      {
        url: "https://ac.goit.global/fullstack/react/og-meta.jpg",
        width: 1200,
        height: 630,
        alt: "Book campervan",
      },
    ],
    type: "website",
  },
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
 }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <TanStackProvider>
          <Header/>
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}


